#!/bin/bash

# Auto-commit daily log script
# Runs daily via cron to maintain GitHub contribution graph

REPO_DIR="/var/www/auto-commit"
LOG_DIR="$REPO_DIR/logs"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)
DAY=$(date +%A)

# Create logs directory
mkdir -p "$LOG_DIR"

# Generate daily log content
cat > "$LOG_DIR/$DATE.md" << EOF
# Daily Log - $DATE

## Date: $DATE ($DAY)
## Time: $TIME

## System Activity
- VPS3 Server: Online
- Databases: $(mysql -u root -p'Keith082703.' -e 'SHOW DATABASES;' 2>/dev/null | wc -l) active
- Websites Hosted: $(ls /var/www/projects/ 2>/dev/null | wc -l) projects

## Services Status
- Nginx: $(systemctl is-active nginx)
- MariaDB: $(systemctl is-active mariadb)
- PHP-FPM: $(systemctl is-active php8.3-fpm)

## Disk Usage
- Total: $(df -h / | awk 'NR==2{print $2}')
- Used: $(df -h / | awk 'NR==2{print $3}')
- Available: $(df -h / | awk 'NR==2{print $4}')

## Memory Usage
- Total: $(free -h | awk 'NR==2{print $2}')
- Used: $(free -h | awk 'NR==2{print $3}')

## Uptime
$(uptime -p)

---
Generated by Keith Torda's VPS3 Auto-Commit System
EOF

# Commit and push
cd "$REPO_DIR"
git add .
git commit -m "Daily log: $DATE - System activity recorded" --allow-empty
git push origin master 2>/dev/null || git push origin main 2>/dev/null

echo "Daily log committed: $DATE"
